BTM

# <center> Capstone Project - Neighborhoods businesses Comparison Using K-Means Clustering, Case of New York vs Toronto (Week 2)</center>
### Applied Data Science Capstone by IBM 

##  Table of Content
* [Introduction: Business Problem](#introduction)
* [Data](#data)
* [Methodology](#methodology)
* [Analysis](#analysis)
* [Results and Discussion](#results)
* [Conclusion](#conclusion)
* [References](#References)



## Introduction: Business Problem <a name="introduction"></a>

### Background
Cities around the World contain certain number of neighborhoods formed of venues naturally distributed in many different way.  The historic need to identify city’s driver factors such as financial incentives, quality of urbanisation, social and food diversities, crime level, housing, education, health, etc, often lead to the exploration of similarity or dissimilarity between cities. 
Comparing venues within neighborhoods in cities helps the orientation of decision making in terms of business investment, immigration or relocation, job hunting and much more.  The analysis in this work is applied to the two most populous and diverse cities of the United State and Canada: New York vs Toronto.

### Problem Definition 
The Neighborhoods businesses comparison of two or more different cities is a type of unsupervised classification where venues have to be segmented and grouped into a certain number of dissimilar and non-overlapping clusters.  These clusters should contain similar venues of common characteristics, without any internal structure or label.  K-Means algorithms is one of the most popular tools of segmentation of unsupervised data that will be used here coupled with foursquare API to make essentially venues calls to retrieve needed information. 

### Stakeholders
This work is particularly targeting business people who need to invest by giving them insight views of market in neighborhoods.  This work concern also at large job seekers to explore possibilities that offer one city over the other.  The results of this work should also advice on people movement, immigration and relocation, because positive numbers on neighborhoods businesses in a city, will most probably influence the influx of people.



## Data <a name="data"></a>

### Data Source

Data used in this work were collected from open sources on the internet.  
For New York, a total of 306 neighborhoods with a total of 5 boroughs in neighborhood as well as the latitude and the longitude of each neighborhood fount on the web under the link: https://geo.nyu.edu/catalog/nyu_2451_34572

For Toronto, City neighborhoods were found on Wikipedia website under the following link:
https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M

This link provided postal codes of venues that could be transform into needed data by using pandas library function.  In case the geocoder package couldn't work, the geographical coordinates of postal code can be found under the link:
http://cocl.us/Geospatial_data
These data will be cleaned and formatted accordingly to adequately feed the k-Means algorithm for convergent clustering.


The necessary lxml data of Toronto City neighborhoods were found on Wikipedia website under the following link: 

https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M

This link provided postal codes of venues that could be transform into needed data by using pandas library function.

In case the geocoder package couldn't work, the geographical coordinates of postal code can be found under the link:

http://cocl.us/Geospatial_data

## 1.3 Downoad of Raw Data 

#### Importing Useful Libraries

In [1]:
# For Python location of important packages
from IPython.core.magic import register_line_magic
import sys
sys.path
import os

# !pip install --upgrade distribute
# !pip install --upgrade setuptools

# !python -m pip install -U pip

# library to handle data in a vectorized manner
import pandas as pd # library for data analsysis
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
from bs4 import BeautifulSoup

# import json # library to handle JSON files

# !conda install -c conda-forge geopy --yes  
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

!pip3 install wget  # Installation of wget for reading webs URL
import wget

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

!conda install -c conda-forge folium=0.5.0 --yes 
import folium # map rendering library

print('Libraries imported.')

ERROR: Invalid requirement: '#'


Solving environment: ...working... done

# All requested packages already installed.

Libraries imported.


### Scraping of Raw Data on Toronto

In [2]:
# Downloading of Data
source = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M").text
soup = BeautifulSoup(source, 'lxml')

table = soup.find("table")
table_rows = table.tbody.find_all("tr")

res = []
for tr in table_rows:
    td = tr.find_all("td")
    row = [tr.text for tr in td]
    
    # Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.
    if row != [] and row[1] != "Not assigned":
        # If a cell has a borough but a "Not assigned" neighborhood, then the neighborhood will be the same as the borough.
        if "Not assigned" in row[2]: 
            row[2] = row[1]
        res.append(row)

# Dataframe with 3 columns
df = pd.DataFrame(res, columns = ["PostalCode", "Borough", "Neighborhood"])

# Show the top 
df.head()

PostalCode             Borough                 Neighborhood
0      M1A\n      Not assigned\n               Not assigned\n
1      M2A\n      Not assigned\n               Not assigned\n
2      M3A\n        North York\n                  Parkwoods\n
3      M4A\n        North York\n           Victoria Village\n
4      M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

Removing "\n" in all columns and display the 12 rows of the dataset

In [3]:
df["PostalCode"] = df["PostalCode"].str.replace("\n","")
df["Borough"] = df["Borough"].str.replace("\n","")
df["Neighborhood"] = df["Neighborhood"].str.replace("\n","")

df = df[df.Neighborhood !='Not assigned'].reset_index() # Cleaning all rows with "Not assigned" in Neighborhood column

df.head(12)

index PostalCode           Borough  \
0       2        M3A        North York   
1       3        M4A        North York   
2       4        M5A  Downtown Toronto   
3       5        M6A        North York   
4       6        M7A  Downtown Toronto   
5       8        M9A         Etobicoke   
6       9        M1B       Scarborough   
7      11        M3B        North York   
8      12        M4B         East York   
9      13        M5B  Downtown Toronto   
10     14        M6B        North York   
11     17        M9B         Etobicoke   

                                         Neighborhood  
0                                           Parkwoods  
1                                    Victoria Village  
2                           Regent Park, Harbourfront  
3                    Lawrence Manor, Lawrence Heights  
4         Queen's Park, Ontario Provincial Government  
5             Islington Avenue, Humber Valley Village  
6                                      Malvern, Rouge  
7                                           Don Mills  
8                     Parkview Hill, Woodbine Gardens  
9                            Garden District, Ryerson  
10                                          Glencairn  
11  West Deane Park, Princess Gardens, Martin Grov...

Grouping Neighborhoods having the same Postal Code

In [4]:
df = df.groupby(["PostalCode", "Borough"])["Neighborhood"].apply(", ".join).reset_index()

df.head(12)

PostalCode      Borough                                       Neighborhood
0         M1B  Scarborough                                     Malvern, Rouge
1         M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2         M1E  Scarborough                  Guildwood, Morningside, West Hill
3         M1G  Scarborough                                             Woburn
4         M1H  Scarborough                                          Cedarbrae
5         M1J  Scarborough                                Scarborough Village
6         M1K  Scarborough        Kennedy Park, Ionview, East Birchmount Park
7         M1L  Scarborough                    Golden Mile, Clairlea, Oakridge
8         M1M  Scarborough    Cliffside, Cliffcrest, Scarborough Village West
9         M1N  Scarborough                        Birch Cliff, Cliffside West
10        M1P  Scarborough  Dorset Park, Wexford Heights, Scarborough Town...
11        M1R  Scarborough                                  Wexford, Maryvale

In [5]:
# Checking the size of the obtained dataset
print("Shape:", df.shape)

Shape: (103, 3)


### Toronto Geographical Coordinates for each Neighborhood

Because the Geocoder couldn't generate geo-coordinates, we used the csv file

In [6]:
df_geo_coor = pd.read_csv("./Geospatial_Coordinates.csv")
df_geo_coor.head(12)

Postal Code   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
5          M1J  43.744734 -79.239476
6          M1K  43.727929 -79.262029
7          M1L  43.711112 -79.284577
8          M1M  43.716316 -79.239476
9          M1N  43.692657 -79.264848
10         M1P  43.757410 -79.273304
11         M1R  43.750072 -79.295849

In [7]:
df_toronto = pd.merge(df, df_geo_coor, how='left', left_on = 'PostalCode', right_on = 'Postal Code')
# remove the "Postal Code" column
df_toronto.drop("Postal Code", axis=1, inplace=True)
df_toronto.head(12)

PostalCode      Borough                                       Neighborhood  \
0         M1B  Scarborough                                     Malvern, Rouge   
1         M1C  Scarborough             Rouge Hill, Port Union, Highland Creek   
2         M1E  Scarborough                  Guildwood, Morningside, West Hill   
3         M1G  Scarborough                                             Woburn   
4         M1H  Scarborough                                          Cedarbrae   
5         M1J  Scarborough                                Scarborough Village   
6         M1K  Scarborough        Kennedy Park, Ionview, East Birchmount Park   
7         M1L  Scarborough                    Golden Mile, Clairlea, Oakridge   
8         M1M  Scarborough    Cliffside, Cliffcrest, Scarborough Village West   
9         M1N  Scarborough                        Birch Cliff, Cliffside West   
10        M1P  Scarborough  Dorset Park, Wexford Heights, Scarborough Town...   
11        M1R  Scarborough                                  Wexford, Maryvale   

     Latitude  Longitude  
0   43.806686 -79.194353  
1   43.784535 -79.160497  
2   43.763573 -79.188711  
3   43.770992 -79.216917  
4   43.773136 -79.239476  
5   43.744734 -79.239476  
6   43.727929 -79.262029  
7   43.711112 -79.284577  
8   43.716316 -79.239476  
9   43.692657 -79.264848  
10  43.757410 -79.273304  
11  43.750072 -79.295849

### Exploration and Clustering of Neighborhoods in Toronto

#####  Generation of Toronto Latitude and Longitude

In [8]:
address = "Toronto, ON"

geolocator = Nominatim(user_agent="toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto city are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto city are 43.6534817, -79.3839347.


#### Visualization of Toronto Map and Neighborhood Markers

In [14]:
# create map of Toronto using latitude and longitude values
map_toronto = folium.Map(location=[latitude, longitude], zoom_start=10)
map_toronto

# Map with Neighborhoods marked

for lat, lng, borough, neighborhood in zip(
        df_toronto['Latitude'], 
        df_toronto['Longitude'], 
        df_toronto['Borough'], 
        df_toronto['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  

map_toronto

### New York Download and Explore Dataset

#### Loading and Exploring of New York Dataset

In [41]:
import wget
url = 'https://cocl.us/new_york_dataset' 
new_york_dataset = wget.download(url)

print('Data downloaded!')

100% [............................................................................] 115774 / 115774Data downloaded!


In [47]:
import json
with open('new_york_dataset') as json_data:
    newyork_data = json.load(json_data)

newyork_data

{'type': 'FeatureCollection',
 'totalFeatures': 306,
 'features': [{'type': 'Feature',
   'id': 'nyu_2451_34572.1',
   'geometry': {'type': 'Point',
    'coordinates': [-73.84720052054902, 40.89470517661]},
   'geometry_name': 'geom',
   'properties': {'name': 'Wakefield',
    'stacked': 1,
    'annoline1': 'Wakefield',
    'annoline2': None,
    'annoline3': None,
    'annoangle': 0.0,
    'borough': 'Bronx',
    'bbox': [-73.84720052054902,
     40.89470517661,
     -73.84720052054902,
     40.89470517661]}},
  {'type': 'Feature',
   'id': 'nyu_2451_34572.2',
   'geometry': {'type': 'Point',
    'coordinates': [-73.82993910812398, 40.87429419303012]},
   'geometry_name': 'geom',
   'properties': {'name': 'Co-op City',
    'stacked': 2,
    'annoline1': 'Co-op',
    'annoline2': 'City',
    'annoline3': None,
    'annoangle': 0.0,
    'borough': 'Bronx',
    'bbox': [-73.82993910812398,
     40.87429419303012,
     -73.82993910812398,
     40.87429419303012]}},
  {'type': 'Feature',
 

Notice how all the relevant data is in the *features* key, which is basically a list of the neighborhoods. So, let's define a new variable that includes this data.

In [48]:
neighborhoods_data = newyork_data['features']

Let's take a look at the first item in this list.

In [49]:
neighborhoods_data[0]

{'type': 'Feature',
 'id': 'nyu_2451_34572.1',
 'geometry': {'type': 'Point',
  'coordinates': [-73.84720052054902, 40.89470517661]},
 'geometry_name': 'geom',
 'properties': {'name': 'Wakefield',
  'stacked': 1,
  'annoline1': 'Wakefield',
  'annoline2': None,
  'annoline3': None,
  'annoangle': 0.0,
  'borough': 'Bronx',
  'bbox': [-73.84720052054902,
   40.89470517661,
   -73.84720052054902,
   40.89470517661]}}

#### Tranform the data into a *pandas* dataframe

The next task is essentially transforming this data of nested Python dictionaries into a *pandas* dataframe. So let's start by creating an empty dataframe.

In [50]:
# define the dataframe columns
column_names = ['Borough', 'Neighborhood', 'Latitude', 'Longitude'] 

# instantiate the dataframe
neighborhoods = pd.DataFrame(columns=column_names)

Take a look at the empty dataframe to confirm that the columns are as intended.

In [51]:
neighborhoods

Empty DataFrame
Columns: [Borough, Neighborhood, Latitude, Longitude]
Index: []

Then let's loop through the data and fill the dataframe one row at a time.

In [52]:
for data in neighborhoods_data:
    borough = neighborhood_name = data['properties']['borough'] 
    neighborhood_name = data['properties']['name']
        
    neighborhood_latlon = data['geometry']['coordinates']
    neighborhood_lat = neighborhood_latlon[1]
    neighborhood_lon = neighborhood_latlon[0]
    
    neighborhoods = neighborhoods.append({'Borough': borough,
                                          'Neighborhood': neighborhood_name,
                                          'Latitude': neighborhood_lat,
                                          'Longitude': neighborhood_lon}, ignore_index=True)

Quickly examine the resulting dataframe.

In [53]:
neighborhoods.head(12)

Borough    Neighborhood   Latitude  Longitude
0       Bronx       Wakefield  40.894705 -73.847201
1       Bronx      Co-op City  40.874294 -73.829939
2       Bronx     Eastchester  40.887556 -73.827806
3       Bronx       Fieldston  40.895437 -73.905643
4       Bronx       Riverdale  40.890834 -73.912585
5       Bronx     Kingsbridge  40.881687 -73.902818
6   Manhattan     Marble Hill  40.876551 -73.910660
7       Bronx        Woodlawn  40.898273 -73.867315
8       Bronx         Norwood  40.877224 -73.879391
9       Bronx  Williamsbridge  40.881039 -73.857446
10      Bronx      Baychester  40.866858 -73.835798
11      Bronx  Pelham Parkway  40.857413 -73.854756

It is found that the dataset has all 5 boroughs and 306 neighborhoods.

In [54]:
print('The dataframe has {} boroughs and {} neighborhoods.'.format(
        len(neighborhoods['Borough'].unique()),
        neighborhoods.shape[0]
      )
)

The dataframe has 5 boroughs and 306 neighborhoods.


#### Use geopy library to get the latitude and longitude values of New York City.

In order to define an instance of the geocoder, we need to define a user_agent. We will name our agent <em>ny_explorer</em>, as shown below.

In [55]:
address = 'New York City, NY'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of New York City are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of New York City are 40.7127281, -74.0060152.


#### Create a map of New York with neighborhoods superimposed on top.

In [58]:
# create map of New York using latitude and longitude values
map_newyork = folium.Map(location=[latitude, longitude], zoom_start=10)

# add markers to map
for lat, lng, borough, neighborhood in zip(neighborhoods['Latitude'], neighborhoods['Longitude'], neighborhoods['Borough'], neighborhoods['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='yellow',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_newyork)  
    
map_newyork

However, for illustration purposes, let's simplify the above map and segment and cluster only the neighborhoods in Manhattan. So let's slice the original dataframe and create a new dataframe of the Manhattan data.


## Methodology <a name="methodology"></a>

Having neighborhoods of Toronto and New York, to find venues in these neighborhoods, Foursquare API is used. With explored, k-Means is used to segment venues into clusters. By comparing similar clusters of the two city, we will be able to conclude on the level of business activities into the city; this is not to confuse with the number of enterprises in each city.

###  Using Foursquare API

My Foursquare Credentials, hiden to public on GitHub repository

In [59]:
# @hidden_cell
CLIENT_ID = 'KNWPZDKIHCJVP3WR4EXNDSFHF1CIOEOFXAZJP5LEBPA4YZMR' # your Foursquare ID
CLIENT_SECRET = 'JVBQSID1P1YJ5FF1EH2VEDXVKX0M5DMWNESJLL41FHAL5ZP4' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

### On Toronto
Let explore the first neighborhood in the dataframe 'df_toronto'

In [60]:
neighborhood_name = df_toronto_denc.loc[0, 'Neighborhood']
print(f"The first neighborhood's name is '{neighborhood_name}'.")

The first neighborhood's name is 'The Beaches'.


Neighborhood Coordinates

In [62]:
neighborhood_latitude = df_toronto.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = df_toronto.loc[0, 'Longitude'] # neighborhood longitude value

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name, 
                                                               neighborhood_latitude, 
                                                               neighborhood_longitude))

Latitude and longitude values of The Beaches are 43.806686299999996, -79.19435340000001.


#### Now, let's get the top 1000 venues that are in The Beaches within a radius of 10000 meters.

In [64]:
LIMIT = 1000 # limit of number of venues returned by Foursquare API
radius = 10000 # define radius
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)

# get the result to a json file
results = requests.get(url).json()

#### Extracting venue cstegories

In [65]:
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#### Cleaning of Json dataframe

In [66]:
venues = results['response']['groups'][0]['items']
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues

name            categories  \
0                        Toronto Pan Am Sports Centre    Athletics & Sports   
1                         African Rainforest Pavilion           Zoo Exhibit   
2                                         Toronto Zoo                   Zoo   
3                                  Polar Bear Exhibit                   Zoo   
4                                    Morningside Park                  Park   
5                                     Gorilla Exhibit           Zoo Exhibit   
6                 Lamanna's Bakery, Cafe & Fine Foods                Bakery   
7                                   Orangutan Exhibit           Zoo Exhibit   
8                               Australasia Pavillion           Zoo Exhibit   
9                                         Mona's Roti  Caribbean Restaurant   
10                   The Real McCoy Burgers And Pizza          Burger Joint   
11                         Port Union Waterfront Park                  Park   
12                                       The Roti Hut  Caribbean Restaurant   
13                                 Images Salon & Spa                   Spa   
14                                    Penguin Exhibit           Zoo Exhibit   
15                                      China Cottage      Hakka Restaurant   
16                 Nguyen Huong Vietnamese Sandwiches        Sandwich Place   
17                              Glen Rouge Campground            Campground   
18                          Fratelli Village Pizzeria    Italian Restaurant   
19                                    CANBE Foods Inc     Indian Restaurant   
20                                   Rouge Beach Park                  Park   
21                                               LCBO          Liquor Store   
22                     Fahmee Bakery & Jamaican Foods  Caribbean Restaurant   
23                                        Chick-N-Joy   Fried Chicken Joint   
24                                   Shamrock Burgers          Burger Joint   
25                               Charcoal Kebab House   Xinjiang Restaurant   
26                                   Whittamore Farms                  Farm   
27                                     Guildwood Park                  Park   
28                                             Cora's        Breakfast Spot   
29                                        Pig Out BBQ             BBQ Joint   
30             Remington Parkview Golf & Country Club           Golf Course   
31                              Rouge Beach and Marsh                 Beach   
32                              Thomson Memorial Park                  Park   
33                         The Olde Stone Cottage Pub                   Pub   
34                  Scarborough Golf and Country Club           Golf Course   
35                                        BeaverTails          Dessert Shop   
36                                          Bulk Barn     Food & Drink Shop   
37                                     Highland Creek          Neighborhood   
38                                  Americas Pavillon           Zoo Exhibit   
39                     Jim Chai Kee Wonton Noodle 沾仔記          Noodle House   
40                                           Michaels   Arts & Crafts Store   
41           Fishman Lobster Clubhouse Restaurant 魚樂軒    Chinese Restaurant   
42                                          Wild Wing           Wings Joint   
43                        Chris Jerk Caribbean Bistro  Caribbean Restaurant   
44                     Port Union Village Common Park                  Park   
45                                        Dairy Queen        Ice Cream Shop   
46                                   Ted's Restaurant        Breakfast Spot   
47                 Cornell Community Centre & Library      Community Center   
48           Anjappar Authentic Chettinadu Restaurant     Indian Restaurant   
49                                    Frenchman's Bay                 Beach   
50                  

### Exploration of Neighborhood in Toronto City

Considering an zone in a radius of 10 km

In [68]:
def getNearbyVenues(names, latitudes, longitudes, radius=10000):
    venues_list=[]
    
    for name, lat, lng in zip(names, latitudes, longitudes):
        # print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

Looping the function on each venue to generate a new dataframe named toronto_venues

In [69]:
toronto_venues = getNearbyVenues(names=df_toronto['Neighborhood'],
                                   latitudes=df_toronto['Latitude'],
                                   longitudes=df_toronto['Longitude']
                                  )

toronto_venues.head(10)

Neighborhood  Neighborhood Latitude  Neighborhood Longitude  \
0  Malvern, Rouge              43.806686              -79.194353   
1  Malvern, Rouge              43.806686              -79.194353   
2  Malvern, Rouge              43.806686              -79.194353   
3  Malvern, Rouge              43.806686              -79.194353   
4  Malvern, Rouge              43.806686              -79.194353   
5  Malvern, Rouge              43.806686              -79.194353   
6  Malvern, Rouge              43.806686              -79.194353   
7  Malvern, Rouge              43.806686              -79.194353   
8  Malvern, Rouge              43.806686              -79.194353   
9  Malvern, Rouge              43.806686              -79.194353   

                                 Venue  Venue Latitude  Venue Longitude  \
0         Toronto Pan Am Sports Centre       43.790623       -79.193869   
1          African Rainforest Pavilion       43.817725       -79.183433   
2                          Toronto Zoo       43.820582       -79.181551   
3                   Polar Bear Exhibit       43.823372       -79.185145   
4                     Morningside Park       43.786546       -79.205322   
5                      Gorilla Exhibit       43.819080       -79.184235   
6  Lamanna's Bakery, Cafe & Fine Foods       43.797971       -79.148432   
7                    Orangutan Exhibit       43.818413       -79.182548   
8                Australasia Pavillion       43.822563       -79.183286   
9                          Mona's Roti       43.791613       -79.251015   

         Venue Category  
0    Athletics & Sports  
1           Zoo Exhibit  
2                   Zoo  
3                   Zoo  
4                  Park  
5           Zoo Exhibit  
6                Bakery  
7           Zoo Exhibit  
8           Zoo Exhibit  
9  Caribbean Restaurant

#### Number of venues returned for each Neighborhood

In [70]:
toronto_venues.groupby('Neighborhood').count()

Neighborhood Latitude  \
Neighborhood                                                                
Agincourt                                                             100   
Alderwood, Long Branch                                                100   
Bathurst Manor, Wilson Heights, Downsview North                       100   
Bayview Village                                                       100   
Bedford Park, Lawrence Manor East                                     100   
Berczy Park                                                           100   
Birch Cliff, Cliffside West                                           100   
Brockton, Parkdale Village, Exhibition Place                          100   
Business reply mail Processing Centre, South Ce...                    100   
CN Tower, King and Spadina, Railway Lands, Harb...                    100   
Caledonia-Fairbanks                                                   100   
Canada Post Gateway Processing Centre                                 100   
Cedarbrae                                                             100   
Central Bay Street                                                    100   
Christie                                                              100   
Church and Wellesley                                                  100   
Clarks Corners, Tam O'Shanter, Sullivan                               100   
Cliffside, Cliffcrest, Scarborough Village West                       100   
Commerce Court, Victoria Hotel                                        100   
Davisville                                                            100   
Davisville North                                                      100   
Del Ray, Mount Dennis, Keelsdale and Silverthorn                      100   
Don Mills                                                             200   
Dorset Park, Wexford Heights, Scarborough Town ...                    100   
Downsview                                                             400   
Dufferin, Dovercourt Village                                          100   
East Toronto, Broadview North (Old East York)                         100   
Eringate, Bloordale Gardens, Old Burnhamthorpe,...                    100   
Fairview, Henry Farm, Oriole                                          100   
First Canadian Place, Underground city                                100   
Forest Hill North & West, Forest Hill Road Park                       100   
Garden District, Ryerson                                              100   
Glencairn                                                             100   
Golden Mile, Clairlea, Oakridge                                       100   
Guildwood, Morningside, West Hill                                     100   
Harbourfront East, Union Station, Toronto Islands                     100   
High Park, The Junction South                                         100   
Hillcrest Village                                                     100   
Humber Summit                                                         100   
Humberlea, Emery                                                      100   
Humewood-Cedarvale                                                    100   
India Bazaar, The Beaches West                                        100   
Islington Avenue, Humber Valley Village                               100   
Kennedy Park, Ionview, East Birchmount Park                           100   
Kensington Market, Chinatown, Grange Park                             100   
Kingsview Village, St. Phillips, Martin Grove G...                    100   
Lawrence Manor, Lawrence Heights                                      100   
Lawrence Park                                                         100   
Leaside                                                               100   
Little Portugal, Trinity                                              100   
Malvern, Rouge                                  

#### Number of unique categories can be curated from all the returned venues

In [ ]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

In [72]:
# one hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

toronto_onehot.head(12)

Zoo Exhibit  Afghan Restaurant  African Restaurant  Airport  \
0             0                  0                   0        0   
1             1                  0                   0        0   
2             0                  0                   0        0   
3             0                  0                   0        0   
4             0                  0                   0        0   
5             1                  0                   0        0   
6             0                  0                   0        0   
7             1                  0                   0        0   
8             1                  0                   0        0   
9             0                  0                   0        0   
10            0                  0                   0        0   
11            0                  0                   0        0   

    Airport Lounge  American Restaurant  Aquarium  Art Gallery  \
0                0                    0         0            0   
1                0                    0         0            0   
2                0                    0         0            0   
3                0                    0         0            0   
4                0                    0         0            0   
5                0                    0         0            0   
6                0                    0         0            0   
7                0                    0         0            0   
8                0                    0         0            0   
9                0                    0         0            0   
10               0                    0         0            0   
11               0                    0         0            0   

    Arts & Crafts Store  Asian Restaurant  Athletics & Sports  \
0                     0                 0                   1   
1                     0                 0                   0   
2                     0                 0                   0   
3                     0                 0                   0   
4                     0                 0                   0   
5                     0                 0                   0   
6                     0                 0                   0   
7                     0                 0                   0   
8                     0                 0                   0   
9                     0                 0                   0   
10                    0                 0                   0   
11                    0                 0                   0   

    Auto Dealership  Automotive Shop  BBQ Joint  Bagel Shop  Bakery  Bar  \
0                 0                0          0           0       0    0   
1                 0                0          0           0       0    0   
2                 0                0          0           0       0    0   
3                 0                0          0           0       0    0   
4                 0                0          0           0       0    0   
5                 0                0          0           0       0    0   
6                 0                0          0           0       1    0   
7                 0                0          0           0       0    0   
8                 0                0          0           0       0    0   
9                 0                0          0           0       0    0   
10                0                0          0           0       0    0   
11                0                0          0           0       0    0   

    Baseball Stadium  Basketball Stadium  Beach  Beer Bar  Beer Store  Bistro  \
0                  0                   0      0         0           0       0   
1                  0                   0      0         0           0       0   
2                  0                   0      0         0           0       0   
3                  0                   0      0         0           0       0   
4                  0             

#### Grouping rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [73]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped.head(12)

Neighborhood  Zoo Exhibit  \
0                                           Agincourt         0.04   
1                              Alderwood, Long Branch         0.00   
2     Bathurst Manor, Wilson Heights, Downsview North         0.00   
3                                     Bayview Village         0.00   
4                   Bedford Park, Lawrence Manor East         0.00   
5                                         Berczy Park         0.00   
6                         Birch Cliff, Cliffside West         0.00   
7        Brockton, Parkdale Village, Exhibition Place         0.00   
8   Business reply mail Processing Centre, South C...         0.00   
9   CN Tower, King and Spadina, Railway Lands, Har...         0.00   
10                                Caledonia-Fairbanks         0.00   
11              Canada Post Gateway Processing Centre         0.00   

    Afghan Restaurant  African Restaurant  Airport  Airport Lounge  \
0                0.00                 0.0     0.00            0.00   
1                0.00                 0.0     0.00            0.00   
2                0.00                 0.0     0.01            0.00   
3                0.00                 0.0     0.00            0.00   
4                0.01                 0.0     0.00            0.00   
5                0.00                 0.0     0.00            0.00   
6                0.01                 0.0     0.00            0.00   
7                0.00                 0.0     0.00            0.00   
8                0.00                 0.0     0.00            0.00   
9                0.00                 0.0     0.00            0.00   
10               0.00                 0.0     0.00            0.00   
11               0.01                 0.0     0.00            0.01   

    American Restaurant  Aquarium  Art Gallery  Arts & Crafts Store  \
0                  0.00      0.00         0.00                 0.01   
1                  0.00      0.00         0.00                 0.01   
2                  0.00      0.00         0.00                 0.00   
3                  0.00      0.00         0.00                 0.00   
4                  0.00      0.00         0.00                 0.00   
5                  0.01      0.01         0.01                 0.01   
6                  0.01      0.00         0.00                 0.00   
7                  0.00      0.01         0.01                 0.01   
8                  0.02      0.00         0.01                 0.00   
9                  0.01      0.01         0.01                 0.01   
10                 0.00      0.00         0.01                 0.01   
11                 0.01      0.00         0.00                 0.01   

    Asian Restaurant  Athletics & Sports  Auto Dealership  Automotive Shop  \
0               0.01                0.01              0.0              0.0   
1               0.00                0.00              0.0              0.0   
2               0.00                0.00              0.0              0.0   
3               0.00                0.00              0.0              0.0   
4               0.00                0.00              0.0              0.0   
5               0.00                0.01              0.0              0.0   
6               0.01                0.01              0.0              0.0   
7               0.00                0.00              0.0              0.0   
8               0.00                0.01              0.0              0.0   
9               0.00                0.00              0.0              0.0   
10              0.00                0.00              0.0              0.0   
11              0.01                0.00              0.0              0.0   

    BBQ Joint  Bagel Shop  Bakery   Bar  Baseball Stadium  Basketball Stadium  \
0        0.01        0.00    0.02  0.00              0.00                0.00   
1        0.01        0.00    0.05  0.00              0.00                0.00   
2        0.01        0.02    0.03  0.

#### Checking the 10 most common venues in each neighborhood.

In [74]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    return row_categories_sorted.index.values[0:num_top_venues]

num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head(10)

Neighborhood  \
0                                          Agincourt   
1                             Alderwood, Long Branch   
2    Bathurst Manor, Wilson Heights, Downsview North   
3                                    Bayview Village   
4                  Bedford Park, Lawrence Manor East   
5                                        Berczy Park   
6                        Birch Cliff, Cliffside West   
7       Brockton, Parkdale Village, Exhibition Place   
8  Business reply mail Processing Centre, South C...   
9  CN Tower, King and Spadina, Railway Lands, Har...   

       1st Most Common Venue      2nd Most Common Venue 3rd Most Common Venue  \
0  Middle Eastern Restaurant                Supermarket  Caribbean Restaurant   
1                Coffee Shop                       Park                Bakery   
2                Coffee Shop                       Park    Italian Restaurant   
3                Coffee Shop  Middle Eastern Restaurant                Bakery   
4                       Park         Italian Restaurant                  Café   
5                Coffee Shop                       Park                  Café   
6                       Park                Coffee Shop                  Café   
7                       Park                       Café               Brewery   
8                Coffee Shop                       Park                  Café   
9                       Park                Coffee Shop                  Café   

       4th Most Common Venue 5th Most Common Venue 6th Most Common Venue  \
0                Zoo Exhibit                  Park          Liquor Store   
1               Burger Joint    Seafood Restaurant          Liquor Store   
2  Middle Eastern Restaurant                  Café        Clothing Store   
3        Japanese Restaurant    Chinese Restaurant            Bagel Shop   
4                Coffee Shop                Bakery          Liquor Store   
5                     Bakery                 Diner                 Hotel   
6                      Beach               Brewery        Farmers Market   
7                 Restaurant                Bakery           Pizza Place   
8                      Beach        Farmers Market             Gastropub   
9                     Bakery            Restaurant              Beer Bar   

  7th Most Common Venue          8th Most Common Venue  \
0         Grocery Store              Indian Restaurant   
1         Grocery Store                    Pizza Place   
2     Korean Restaurant                    Supermarket   
3                  Park                   Dessert Shop   
4            Restaurant                          Hotel   
5        Sandwich Place  Vegetarian / Vegan Restaurant   
6         Grocery Store                         Bakery   
7                   Bar                       Beer Bar   
8         Historic Site                        Brewery   
9        Sandwich Place                          Hotel   

    9th Most Common Venue  10th Most Common Venue  
0     Japanese Restaurant              Restaurant  
1     Sporting Goods Shop          Ice Cream Shop  
2  Furniture / Home Store           Grocery Store  
3             Supermarket       Korean Restaurant  
4            Dessert Shop  Furniture / Home Store  
5              Restaurant           Historic Site  
6             Pizza Place    Caribbean Restaurant  
7      Italian Restaurant          Sandwich Place  
8     Japanese Restaurant                  Bakery  
9                   Diner     Japanese Restaurant


## Analysis <a name="analysis"></a>

##### Running k-Means algorithm to group neighborhood into clusters. Let take k = 5

In [75]:
# set number of clusters = 5
kclusters = 5

toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

array([0, 4, 2, 2, 1, 3, 3, 1, 3, 3])

#### New dataframe of top 10 venues for each neighborhood

In [105]:
# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_,'false')

toronto_merged = df_toronto

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on ='Neighborhood')

# Drop of duplicate column
toronto_merged = toronto_merged.T.drop_duplicates().T

toronto_merged.head() # check the last columns!

PostalCode      Borough                            Neighborhood Latitude  \
0        M1B  Scarborough                          Malvern, Rouge  43.8067   
1        M1C  Scarborough  Rouge Hill, Port Union, Highland Creek  43.7845   
2        M1E  Scarborough       Guildwood, Morningside, West Hill  43.7636   
3        M1G  Scarborough                                  Woburn   43.771   
4        M1H  Scarborough                               Cedarbrae  43.7731   

  Longitude Cluster Labels 1st Most Common Venue 2nd Most Common Venue  \
0  -79.1944              0           Zoo Exhibit                  Park   
1  -79.1605              0           Coffee Shop                  Park   
2  -79.1887              0                  Park           Zoo Exhibit   
3  -79.2169              0                  Park  Caribbean Restaurant   
4  -79.2395              0  Caribbean Restaurant     Indian Restaurant   

  3rd Most Common Venue      4th Most Common Venue 5th Most Common Venue  \
0           Supermarket             Ice Cream Shop  Caribbean Restaurant   
1        Ice Cream Shop          Indian Restaurant           Zoo Exhibit   
2  Caribbean Restaurant               Burger Joint         Grocery Store   
3     Indian Restaurant                Zoo Exhibit          Burger Joint   
4                  Park  Middle Eastern Restaurant                Bakery   

  6th Most Common Venue      7th Most Common Venue 8th Most Common Venue  \
0              Pharmacy              Grocery Store          Burger Joint   
1           Supermarket                      Beach  Caribbean Restaurant   
2           Coffee Shop             Breakfast Spot                 Beach   
3         Grocery Store  Middle Eastern Restaurant           Supermarket   
4         Grocery Store                        Gym           Supermarket   

  9th Most Common Venue 10th Most Common Venue  
0        Breakfast Spot   Fast Food Restaurant  
1                   Gym           Liquor Store  
2           Supermarket              Bookstore  
3           Coffee Shop                 Bakery  
4           Coffee Shop           Burger Joint

#### Finally, let's visualize the resulting clusters 

In [138]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []

for lat, lon, poi, cluster in zip(
        toronto_merged['Latitude'], 
        toronto_merged['Longitude'], 
        toronto_merged['Neighborhood'], 
        toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
       fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

###  Toronto Neighborhoods Clustering Examination

Exam of each cluster and determine the discriminating venue categories that distinguish each cluster.

#### Ctuster 1

In [108]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough Cluster Labels      1st Most Common Venue  \
0   Scarborough              0                Zoo Exhibit   
1   Scarborough              0                Coffee Shop   
2   Scarborough              0                       Park   
3   Scarborough              0                       Park   
4   Scarborough              0       Caribbean Restaurant   
5   Scarborough              0                       Park   
6   Scarborough              0                       Park   
8   Scarborough              0                       Park   
10  Scarborough              0                       Park   
11  Scarborough              0                       Park   
12  Scarborough              0  Middle Eastern Restaurant   
16  Scarborough              0                Zoo Exhibit   

        2nd Most Common Venue 3rd Most Common Venue  \
0                        Park           Supermarket   
1                        Park        Ice Cream Shop   
2                 Zoo Exhibit  Caribbean Restaurant   
3        Caribbean Restaurant     Indian Restaurant   
4           Indian Restaurant                  Park   
5        Caribbean Restaurant           Coffee Shop   
6                       Beach           Coffee Shop   
8                       Beach           Coffee Shop   
10       Caribbean Restaurant           Coffee Shop   
11  Middle Eastern Restaurant  Caribbean Restaurant   
12                Supermarket  Caribbean Restaurant   
16                       Park  Caribbean Restaurant   

        4th Most Common Venue      5th Most Common Venue  \
0              Ice Cream Shop       Caribbean Restaurant   
1           Indian Restaurant                Zoo Exhibit   
2                Burger Joint              Grocery Store   
3                 Zoo Exhibit               Burger Joint   
4   Middle Eastern Restaurant                     Bakery   
5                Burger Joint  Middle Eastern Restaurant   
6                        Café       Caribbean Restaurant   
8           Indian Restaurant                    Brewery   
10                Supermarket               Burger Joint   
11                       Café                Supermarket   
12                Zoo Exhibit                       Park   
16          Indian Restaurant         Chinese Restaurant   

        6th Most Common Venue      7th Most Common Venue  \
0                    Pharmacy              Grocery Store   
1                 Supermarket                      Beach   
2                 Coffee Shop             Breakfast Spot   
3               Grocery Store  Middle Eastern Restaurant   
4               Grocery Store                        Gym   
5           Indian Restaurant              Grocery Store   
6                Burger Joint          Indian Restaurant   
8   Middle Eastern Restaurant               Burger Joint   
10  Middle Eastern Restaurant              Burrito Place   
11              Grocery Store          Indian Restaurant   
12               Liquor Store              Grocery Store   
16                Supermarket               Burger Joint   

   8th Most Common Venue      9th Most Common Venue 10th Most Common Venue  
0           Burger Joint             Breakfast Spot   Fast Food Restaurant  
1   Caribbean Restaurant                        Gym           Liquor Store  
2                  Beach                Supermarket              Bookstore  
3            Supermarket                Coffee Shop                 Bakery  
4            Supermarket                Coffee Shop           Burger Joint  
5         Ice Cream Shop                      Beach                    Gym  
6                Brewery  Middle Eastern Restaurant          Grocery Store  
8          Grocery Store                       Café   Caribbean Restaurant  
10     Indian Restaurant              Grocery Store     Italian Restaurant  
11        Breakfast Spot               Liquor Store                 Bakery  
12     Indian Restaurant        Japanese Restaurant             Restaurant  
16      Asia

####  Cluster 2

In [109]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 1, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough Cluster Labels 1st Most Common Venue  \
26        North York              1                  Park   
27        North York              1                  Park   
34        North York              1                  Park   
35         East York              1                  Park   
44   Central Toronto              1                  Park   
45   Central Toronto              1                  Park   
46   Central Toronto              1                  Park   
47   Central Toronto              1                  Park   
49   Central Toronto              1                  Park   
62        North York              1                  Park   
63   Central Toronto              1                  Park   
64   Central Toronto              1                  Park   
65   Central Toronto              1                  Park   
66  Downtown Toronto              1                  Park   
67  Downtown Toronto              1                  Park   
71        North York              1                  Park   
72        North York              1                  Park   
73              York              1                  Park   
74              York              1                  Park   
75  Downtown Toronto              1                  Park   
76      West Toronto              1                  Park   
77      West Toronto              1                  Park   
78      West Toronto              1                  Park   
79        North York              1                  Park   
80              York              1                  Park   
81              York              1                  Park   
82      West Toronto              1                  Park   
83      West Toronto              1                  Park   
84      West Toronto              1                  Park   
88         Etobicoke              1                  Park   
90         Etobicoke              1                  Park   
91         Etobicoke              1                  Park   
92         Etobicoke              1                  Park   
93         Etobicoke              1                  Park   
98              York              1                  Café   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
26                  Café    Italian Restaurant                Bakery   
27                  Café    Italian Restaurant                Bakery   
34                  Café               Brewery                 Beach   
35                  Café                 Beach               Brewery   
44                  Café           Coffee Shop                 Hotel   
45                  Café           Coffee Shop                Bakery   
46                  Café           Coffee Shop    Italian Restaurant   
47                  Café           Coffee Shop               Brewery   
49                  Café           Coffee Shop            Restaurant   
62    Italian Restaurant                  Café           Coffee Shop   
63                  Café   Japanese Restaurant           Coffee Shop   
64                  Café            Restaurant           Coffee Shop   
65                  Café           Coffee Shop    Italian Restaurant   
66                  Café           Coffee Shop    Italian Restaurant   
67                  Café            Restaurant           Coffee Shop   
71                  Café         Grocery Store            Restaurant   
72                  Café           Coffee Shop         Grocery Store   
73                  Café           Coffee Shop            Restaurant   
74                  Café            Restaurant           Coffee Shop   
75                  Café                Bakery            Restaurant   
76                  Café                Bakery            Restaurant   
77                  Café            Restaurant                Bakery   
78                  Café               Brewery            Restaurant   
79                  Café            Restaurant         Grocery Store   
80              

#### Cluster 3

In [110]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 2, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough Cluster Labels      1st Most Common Venue  \
13  Scarborough              2  Middle Eastern Restaurant   
14  Scarborough              2                Supermarket   
15  Scarborough              2                Supermarket   
17   North York              2         Chinese Restaurant   
18   North York              2       Caribbean Restaurant   
19   North York              2                Coffee Shop   
20   North York              2                       Café   
21   North York              2                Coffee Shop   
22   North York              2                Supermarket   
23   North York              2                       Café   
24   North York              2                Coffee Shop   
25   North York              2       Caribbean Restaurant   
28   North York              2                Coffee Shop   
29   North York              2                Coffee Shop   

        2nd Most Common Venue      3rd Most Common Venue  \
13                Supermarket       Caribbean Restaurant   
14       Caribbean Restaurant  Middle Eastern Restaurant   
15       Caribbean Restaurant         Chinese Restaurant   
17  Middle Eastern Restaurant       Caribbean Restaurant   
18                     Bakery         Chinese Restaurant   
19  Middle Eastern Restaurant                     Bakery   
20                       Park  Middle Eastern Restaurant   
21                 Bagel Shop        Japanese Restaurant   
22                 Bagel Shop                Coffee Shop   
23                Coffee Shop                       Park   
24  Middle Eastern Restaurant                       Park   
25                       Café              Grocery Store   
28                       Park         Italian Restaurant   
29                      Hotel  Middle Eastern Restaurant   

        4th Most Common Venue      5th Most Common Venue  \
13         Chinese Restaurant                 Restaurant   
14         Chinese Restaurant                       Park   
15  Middle Eastern Restaurant              Grocery Store   
17        Japanese Restaurant                Supermarket   
18  Middle Eastern Restaurant                Supermarket   
19        Japanese Restaurant         Chinese Restaurant   
20         Italian Restaurant                Coffee Shop   
21  Middle Eastern Restaurant                Supermarket   
22  Middle Eastern Restaurant                       Park   
23         Italian Restaurant  Middle Eastern Restaurant   
24                 Bagel Shop               Liquor Store   
25                     Bakery                       Park   
28  Middle Eastern Restaurant                       Café   
29                 Steakhouse              Grocery Store   

        6th Most Common Venue   7th Most Common Venue 8th Most Common Venue  \
13        Japanese Restaurant            Liquor Store     Indian Restaurant   
14               Noodle House                  Bakery          Dessert Shop   
15                       Park            Dessert Shop   Japanese Restaurant   
17           Sushi Restaurant       Korean Restaurant                Bakery   
18           Sushi Restaurant           Grocery Store                  Park   
19                 Bagel Shop                    Park          Dessert Shop   
20           Sushi Restaurant                  Bakery          Liquor Store   
21                     Bakery                    Park          Dessert Shop   
22                       Café  Furniture / Home Store                Bakery   
23               Liquor Store          Clothing Store            Restaurant   
24             Clothing Store      Italian Restaurant           Supermarket   
25  Middle Eastern Restaurant            Liquor Store        Sandwich Place   
28             Clothing Store       Korean Restaurant           Supermarket   
29             Sandwich Place          Clothing Store     Korean Restaurant   

     9th Most Common Venue  10th Most Common Venue  
13           Grocery Store               BBQ Joint 

#### Cluster 4

In [111]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 3, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough Cluster Labels 1st Most Common Venue  \
7        Scarborough              3                  Park   
9        Scarborough              3                  Park   
36         East York              3                  Park   
37      East Toronto              3                  Park   
38         East York              3                  Park   
39         East York              3                  Park   
40         East York              3                  Park   
41      East Toronto              3                  Park   
42      East Toronto              3           Coffee Shop   
43      East Toronto              3           Coffee Shop   
48   Central Toronto              3                  Park   
50  Downtown Toronto              3                  Café   
51  Downtown Toronto              3                  Park   
52  Downtown Toronto              3           Coffee Shop   
53  Downtown Toronto              3           Coffee Shop   
54  Downtown Toronto              3           Coffee Shop   
55  Downtown Toronto              3                  Park   
56  Downtown Toronto              3           Coffee Shop   
57  Downtown Toronto              3                  Park   
58  Downtown Toronto              3                  Park   
59  Downtown Toronto              3           Coffee Shop   
60  Downtown Toronto              3                  Park   
61  Downtown Toronto              3           Coffee Shop   
68  Downtown Toronto              3                  Park   
69  Downtown Toronto              3                  Park   
70  Downtown Toronto              3           Coffee Shop   
85  Downtown Toronto              3                  Park   
87      East Toronto              3           Coffee Shop   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
7            Coffee Shop                  Café         Grocery Store   
9            Coffee Shop                  Café                 Beach   
36           Coffee Shop                  Café        Farmers Market   
37           Coffee Shop                  Café                 Beach   
38                  Café           Coffee Shop                Bakery   
39           Coffee Shop                  Café                Bakery   
40           Coffee Shop        Farmers Market                  Café   
41           Coffee Shop                  Café                 Hotel   
42                  Park                  Café        Farmers Market   
43                  Park                  Café        Farmers Market   
48           Coffee Shop                  Café             Gastropub   
50           Coffee Shop                  Park                 Diner   
51           Coffee Shop                  Café                 Hotel   
52                  Café                  Park            Restaurant   
53                  Park                  Café                 Hotel   
54                  Park                  Café                 Hotel   
55           Coffee Shop                  Café                 Diner   
56                  Park                  Café                Bakery   
57           Coffee Shop                  Café            Restaurant   
58           Coffee Shop                  Café                Bakery   
59                  Park                  Café                Bakery   
60           Coffee Shop                  Café                Bakery   
61                  Park                  Café                Bakery   
68           Coffee Shop                  Café                Bakery   
69           Coffee Shop                  Café                Bakery   
70                  Park                  Café                Bakery   
85           Coffee Shop                  Café                Bakery   
87                  Park                  Café                 Beach   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
7                Brewery                 Beach          Liquor Store   
9         

#### Cluster 5

In [112]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 4, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough Cluster Labels 1st Most Common Venue 2nd Most Common Venue  \
30    North York              4           Coffee Shop                  Café   
31    North York              4           Coffee Shop                  Café   
32    North York              4           Coffee Shop                  Café   
33    North York              4           Coffee Shop                  Café   
86   Mississauga              4                Bakery     Indian Restaurant   
89     Etobicoke              4           Coffee Shop                  Park   
94     Etobicoke              4                  Park           Coffee Shop   
95     Etobicoke              4                Bakery          Burger Joint   
96    North York              4    Italian Restaurant                 Hotel   
97    North York              4                 Hotel     Indian Restaurant   
99     Etobicoke              4                  Park         Grocery Store   
100    Etobicoke              4                  Park         Grocery Store   
101    Etobicoke              4                 Hotel    Italian Restaurant   
102    Etobicoke              4                 Hotel         Grocery Store   

    3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
30     Italian Restaurant                  Park         Grocery Store   
31     Italian Restaurant                  Park         Grocery Store   
32     Italian Restaurant                  Park         Grocery Store   
33     Italian Restaurant                  Park         Grocery Store   
86          Grocery Store                  Park          Liquor Store   
89                 Bakery          Burger Joint    Seafood Restaurant   
94                 Bakery                  Café            Restaurant   
95          Grocery Store    Seafood Restaurant           Coffee Shop   
96           Liquor Store            Restaurant                Bakery   
97     Chinese Restaurant    Italian Restaurant            Steakhouse   
99                   Café            Restaurant                 Hotel   
100     Indian Restaurant                 Hotel            Restaurant   
101            Steakhouse           Coffee Shop            Restaurant   
102     Indian Restaurant           Coffee Shop                Bakery   

         6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
30                Liquor Store        Clothing Store            Steakhouse   
31                Liquor Store        Clothing Store            Steakhouse   
32                Liquor Store        Clothing Store            Steakhouse   
33                Liquor Store        Clothing Store            Steakhouse   
86               Burrito Place            Restaurant        Breakfast Spot   
89                Liquor Store         Grocery Store           Pizza Place   
94                Burger Joint         Grocery Store        Ice Cream Shop   
95                Liquor Store   Japanese Restaurant   Sporting Goods Shop   
96                  Steakhouse   Sporting Goods Shop      Sushi Restaurant   
97                  Restaurant         Grocery Store           Coffee Shop   
99   Middle Eastern Restaurant            Steakhouse               Brewery   
100  Middle Eastern Restaurant           Coffee Shop   Japanese Restaurant   
101         Chinese Restaurant      Asian Restaurant                 Diner   
102               Liquor Store      Asian Restaurant            Steakhouse   

    9th Most Common Venue       10th Most Common Venue  
30                 Bakery                   Restaurant  
31                 Bakery                   Restaurant  
32                 Bakery                   Restaurant  
33                 Bakery                   Restaurant  
86    Sporting Goods Shop                  Coffee Shop  
89    Sporting Goods Shop               Ice Cream Shop  
94         Sandwich Place          Sporting Goods Shop  
95             Restaurant  Eastern European Restaurant  
96            Supermarket             Asian

## On New York

The same method as above will be applied on New York City.  We have called here the neighborhood dataframe "neighborhoods". We will change this dataframe name to df_newyork with which we will extract the venues using Foursquare API.  Then we will segment and classify into simular clusters. 

In [113]:
# For clarity let rename the New York neighborhood geospatial dataframe as df_newyork 
df_newyork = neighborhoods

In [114]:
df_newyork.head(12)

Borough    Neighborhood   Latitude  Longitude
0       Bronx       Wakefield  40.894705 -73.847201
1       Bronx      Co-op City  40.874294 -73.829939
2       Bronx     Eastchester  40.887556 -73.827806
3       Bronx       Fieldston  40.895437 -73.905643
4       Bronx       Riverdale  40.890834 -73.912585
5       Bronx     Kingsbridge  40.881687 -73.902818
6   Manhattan     Marble Hill  40.876551 -73.910660
7       Bronx        Woodlawn  40.898273 -73.867315
8       Bronx         Norwood  40.877224 -73.879391
9       Bronx  Williamsbridge  40.881039 -73.857446
10      Bronx      Baychester  40.866858 -73.835798
11      Bronx  Pelham Parkway  40.857413 -73.854756

Find the name of the first neighborhood

In [115]:
neighborhood_name = df_newyork.loc[0, 'Neighborhood']
print(f"The first neighborhood's name is '{neighborhood_name}'.")

The first neighborhood's name is 'Wakefield'.


Find geospatial coordinates of Wakefield

In [116]:
neighborhood_latitude = df_newyork.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = df_newyork.loc[0, 'Longitude'] # neighborhood longitude value

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name, 
                                                               neighborhood_latitude, 
                                                               neighborhood_longitude))

Latitude and longitude values of Wakefield are 40.89470517661, -73.84720052054902.


 Let's get the top 1000 venues that are in The Beaches within a radius of 10000 meters.

In [117]:
LIMIT = 1000 # limit of number of venues returned by Foursquare API
radius = 10000 # define radius
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)

# get the result to a json file
results = requests.get(url).json()

Extracting venues categories

In [118]:
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

Cleaning Json dataframe

In [119]:
venues = results['response']['groups'][0]['items']
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues

name  \
0                                  Ripe Kitchen & Bar   
1                                     Ali's Roti Shop   
2                           Anna Artuso's Pastry Shop   
3                                        Rory Dolan's   
4                                         Fish & Ting   
5                                 Avitable Bros. Deli   
6                                        The Heritage   
7         Van Cortlandt Park - John Muir Nature Trail   
8                                     Gourmet Express   
9                                            Foodtown   
10                                     Fairway Market   
11                               Gun Hill Brewing Co.   
12                    New York Bagels Deli & Catering   
13                                  Johnny's Pizzeria   
14                                  Louie & Johnnie's   
15                              Country Thyme Cuisine   
16                                       Panera Bread   
17                                Kinetic Sports Club   
18                                        Nicks Pizza   
19                                 Van Cortlandt Park   
20                                  Sal & Doms Bakery   
21                       Pelham Pizzeria & Ristorante   
22                      The New York Botanical Garden   
23                         Enid A. Haupt Conservatory   
24                                        Shake Shack   
25                            Kingsbridge Social Club   
26                                       White Castle   
27                        Native Plant Garden at NYBG   
28                                          Starbucks   
29  Bronx Park Greenway/NYC Cycling Bike Path/Trai...   
30   The New York Botanical Gardens - The Rock Garden   
31                                Lloyd's Carrot Cake   
32                                         Peach Wave   
33                                Sergio's Restaurant   
34                                     Bronx Alehouse   
35                                 Bronx Burger House   
36                   Van Cortlandt Park Running Track   
37                                    iLoveKickboxing   
38                                DeCicco Food Market   
39                      Peggy Rockefeller Rose Garden   
40                                   Bayou Restaurant   
41                                       Leche y Miel   
42                                  Tortoise And Hare   
43                                 Shop in the Garden   
44                                             Enzo's   
45                                   The Barbecue Pit   
46                              Garden Gourmet Market   
47                            Edgar Allan Poe Cottage   
48                         Bronxville Farmers' Market   
49                                          Tin Marin   
50                              John & Joe's Pizzeria   
51                                      Cocina Chente   
52                           Aoyu Japanese Restaurant   
53                              Bronxville Field Club   
54                     Zeppieri & Sons Italian Bakery   
55                                          Wave Hill   
56                                Tino's Delicatessen   
57                              Ann Clair's Salumeria   
58                                          Bronx Zoo   
59                                   Pizzeria La Rosa   
60                                        Beer Noggin   
61                                 An Beal Bocht Cafe   
62                                 Artuso Pastry Shop   
63                                      Empire Bagels   
64                                          Yo-Burger   
65                                          Starbucks   
66                                    Pelham Bay Park   
67                            Rosie's Bistro Italiano   
68                                             Tilila   
69                                      Sea Lion Pool   
70

### Exploring New York Venues

In [120]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    venues_list=[]
    
    for name, lat, lng in zip(names, latitudes, longitudes):
        # print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

Looping the function on each venue to generate a new dataframe named "newyork_venues"

In [122]:
newyork_venues = getNearbyVenues(names=df_newyork['Neighborhood'],
                                   latitudes=df_newyork['Latitude'],
                                   longitudes=df_newyork['Longitude']
                                  )

newyork_venues.head(12)

Neighborhood  Neighborhood Latitude  Neighborhood Longitude  \
0     Wakefield              40.894705              -73.847201   
1     Wakefield              40.894705              -73.847201   
2     Wakefield              40.894705              -73.847201   
3     Wakefield              40.894705              -73.847201   
4     Wakefield              40.894705              -73.847201   
5     Wakefield              40.894705              -73.847201   
6     Wakefield              40.894705              -73.847201   
7     Wakefield              40.894705              -73.847201   
8     Wakefield              40.894705              -73.847201   
9     Wakefield              40.894705              -73.847201   
10   Co-op City              40.874294              -73.829939   
11   Co-op City              40.874294              -73.829939   

               Venue  Venue Latitude  Venue Longitude  Venue Category  
0   Lollipops Gelato       40.894123       -73.845892    Dessert Shop  
1   Carvel Ice Cream       40.890487       -73.848568  Ice Cream Shop  
2          Walgreens       40.896528       -73.844700        Pharmacy  
3           Rite Aid       40.896649       -73.844846        Pharmacy  
4              Shell       40.894187       -73.845862     Gas Station  
5            Dunkin'       40.890459       -73.849089      Donut Shop  
6             Subway       40.890468       -73.849152  Sandwich Place  
7       Central Deli       40.896728       -73.844387   Deli / Bodega  
8        Louis Pizza       40.898399       -73.848810     Pizza Place  
9    Koss Quick Wash       40.891281       -73.849904      Laundromat  
10    Capri II Pizza       40.876374       -73.829940     Pizza Place  
11          Rite Aid       40.870345       -73.828302        Pharmacy

In [123]:
# Total Number of venues
newyork_venues.shape

(10049, 7)

Number of venues returned for each Neighborhood

In [124]:
newyork_venues.groupby('Neighborhood').count()

Neighborhood Latitude  Neighborhood Longitude  \
Neighborhood                                                               
Allerton                                      29                      29   
Annadale                                       9                       9   
Arden Heights                                  4                       4   
Arlington                                      5                       5   
Arrochar                                      21                      21   
Arverne                                       19                      19   
Astoria                                      100                     100   
Astoria Heights                               13                      13   
Auburndale                                    20                      20   
Bath Beach                                    46                      46   
Battery Park City                             71                      71   
Bay Ridge                                     84                      84   
Bay Terrace                                   47                      47   
Baychester                                    21                      21   
Bayside                                       75                      75   
Bayswater                                      2                       2   
Bedford Park                                  34                      34   
Bedford Stuyvesant                            28                      28   
Beechhurst                                    14                      14   
Bellaire                                      11                      11   
Belle Harbor                                  17                      17   
Bellerose                                     18                      18   
Belmont                                       98                      98   
Bensonhurst                                   25                      25   
Bergen Beach                                   5                       5   
Blissville                                    15                      15   
Bloomfield                                     4                       4   
Boerum Hill                                   83                      83   
Borough Park                                  24                      24   
Breezy Point                                   5                       5   
Briarwood                                     11                      11   
Brighton Beach                                44                      44   
Broad Channel                                  5                       5   
Broadway Junction                             14                      14   
Bronxdale                                     14                      14   
Brooklyn Heights                             100                     100   
Brookville                                     1                       1   
Brownsville                                   17                      17   
Bulls Head                                    47                      47   
Bushwick                                      68                      68   
Butler Manor                                   5                       5   
Cambria Heights                               12                      12   
Canarsie                                       8                       8   
Carnegie Hill                                 91                      91   
Carroll Gardens                              100                     100   
Castle Hill                                    8                       8   
Castleton Corners                             15                      15   
Central Harlem                                45                      45   
Charleston                                    29                      29   
Chelsea                                      107                     107   
Chinatown                                    100                     100   

Number of unique categories can be curated from all the returned venues

In [125]:
print('There are {} uniques categories.'.format(len(newyork_venues['Venue Category'].unique())))

There are 431 uniques categories.


431 uniques categories of venues were found for New York vs 233 in Toronto

### Analysis of similarity in each New York Neighborhood

In [126]:
# one hot encoding
newyork_onehot = pd.get_dummies(newyork_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
newyork_onehot['Neighborhood'] = newyork_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [newyork_onehot.columns[-1]] + list(newyork_onehot.columns[:-1])
newyork_onehot = newyork_onehot[fixed_columns]

newyork_onehot.head()

Zoo Exhibit  Accessories Store  Adult Boutique  Afghan Restaurant  \
0            0                  0               0                  0   
1            0                  0               0                  0   
2            0                  0               0                  0   
3            0                  0               0                  0   
4            0                  0               0                  0   

   African Restaurant  Airport Terminal  American Restaurant  Antique Shop  \
0                   0                 0                    0             0   
1                   0                 0                    0             0   
2                   0                 0                    0             0   
3                   0                 0                    0             0   
4                   0                 0                    0             0   

   Arcade  Arepa Restaurant  Argentinian Restaurant  Art Gallery  Art Museum  \
0       0                 0                       0            0           0   
1       0                 0                       0            0           0   
2       0                 0                       0            0           0   
3       0                 0                       0            0           0   
4       0                 0                       0            0           0   

   Arts & Crafts Store  Arts & Entertainment  Asian Restaurant  \
0                    0                     0                 0   
1                    0                     0                 0   
2                    0                     0                 0   
3                    0                     0                 0   
4                    0                     0                 0   

   Athletics & Sports  Auditorium  Australian Restaurant  Austrian Restaurant  \
0                   0           0                      0                    0   
1                   0           0                      0                    0   
2                   0           0                      0                    0   
3                   0           0                      0                    0   
4                   0           0                      0                    0   

   Automotive Shop  BBQ Joint  Baby Store  Bagel Shop  Bakery  Bank  Bar  \
0                0          0           0           0       0     0    0   
1                0          0           0           0       0     0    0   
2                0          0           0           0       0     0    0   
3                0          0           0           0       0     0    0   
4                0          0           0           0       0     0    0   

   Baseball Field  Baseball Stadium  Basketball Court  Bath House  Beach  \
0               0                 0                 0           0      0   
1               0                 0                 0           0      0   
2               0                 0                 0           0      0   
3               0                 0                 0           0      0   
4               0                 0                 0           0      0   

   Beach Bar  Beer Bar  Beer Garden  Beer Store  Big Box Store  \
0          0         0            0           0              0   
1          0         0            0           0              0   
2          0         0            0           0              0   
3          0         0            0           0              0   
4          0         0            0           0              0   

   Bike Rental / Bike Share  Bike Shop  Bike Trail  Bistro  Board Shop  \
0                         0          0           0       0           0   
1                         0          0           0       0           0   
2                         0          0           0       0           0   
3                         0          0           0       0           0   
4                         0          0           0     

Grouping rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [127]:
newyork_grouped = newyork_onehot.groupby('Neighborhood').mean().reset_index()
newyork_grouped.head(12)

Neighborhood  Zoo Exhibit  Accessories Store  Adult Boutique  \
0            Allerton          0.0                0.0             0.0   
1            Annadale          0.0                0.0             0.0   
2       Arden Heights          0.0                0.0             0.0   
3           Arlington          0.0                0.0             0.0   
4            Arrochar          0.0                0.0             0.0   
5             Arverne          0.0                0.0             0.0   
6             Astoria          0.0                0.0             0.0   
7     Astoria Heights          0.0                0.0             0.0   
8          Auburndale          0.0                0.0             0.0   
9          Bath Beach          0.0                0.0             0.0   
10  Battery Park City          0.0                0.0             0.0   
11          Bay Ridge          0.0                0.0             0.0   

    Afghan Restaurant  African Restaurant  Airport Terminal  \
0                 0.0                 0.0               0.0   
1                 0.0                 0.0               0.0   
2                 0.0                 0.0               0.0   
3                 0.0                 0.0               0.0   
4                 0.0                 0.0               0.0   
5                 0.0                 0.0               0.0   
6                 0.0                 0.0               0.0   
7                 0.0                 0.0               0.0   
8                 0.0                 0.0               0.0   
9                 0.0                 0.0               0.0   
10                0.0                 0.0               0.0   
11                0.0                 0.0               0.0   

    American Restaurant  Antique Shop  Arcade  Arepa Restaurant  \
0              0.000000           0.0     0.0               0.0   
1              0.000000           0.0     0.0               0.0   
2              0.000000           0.0     0.0               0.0   
3              0.200000           0.0     0.0               0.0   
4              0.000000           0.0     0.0               0.0   
5              0.000000           0.0     0.0               0.0   
6              0.010000           0.0     0.0               0.0   
7              0.000000           0.0     0.0               0.0   
8              0.050000           0.0     0.0               0.0   
9              0.000000           0.0     0.0               0.0   
10             0.014085           0.0     0.0               0.0   
11             0.035714           0.0     0.0               0.0   

    Argentinian Restaurant  Art Gallery  Art Museum  Arts & Crafts Store  \
0                      0.0          0.0         0.0                  0.0   
1                      0.0          0.0         0.0                  0.0   
2                      0.0          0.0         0.0                  0.0   
3                      0.0          0.0         0.0                  0.0   
4                      0.0          0.0         0.0                  0.0   
5                      0.0          0.0         0.0                  0.0   
6                      0.0          0.0         0.0                  0.0   
7                      0.0          0.0         0.0                  0.0   
8                      0.0          0.0         0.0                  0.0   
9                      0.0          0.0         0.0                  0.0   
10                     0.0          0.0         0.0                  0.0   
11                     0.0          0.0         0.0                  0.0   

    Arts & Entertainment  Asian Restaurant  Athletics & Sports  Auditorium  \
0                    0.0          0.000000            0.000000    0.000000   
1                    0.0          0.000000            0.000000    0.000000   
2                    0.0          0.000000            0.000000    0.000000   
3                    0.0          0.000000            0.000000    

Checking the 12 most common venues in each neighborhood

In [128]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    return row_categories_sorted.index.values[0:num_top_venues]

num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
nyneighborhoods_venues_sorted = pd.DataFrame(columns=columns)
nyneighborhoods_venues_sorted['Neighborhood'] = newyork_grouped['Neighborhood']

for ind in np.arange(newyork_grouped.shape[0]):
    nyneighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(newyork_grouped.iloc[ind, :], num_top_venues)

nyneighborhoods_venues_sorted.head(12)

Neighborhood 1st Most Common Venue      2nd Most Common Venue  \
0            Allerton           Pizza Place              Deli / Bodega   
1            Annadale           Pizza Place               Dance Studio   
2       Arden Heights   Rental Car Location                Coffee Shop   
3           Arlington         Deli / Bodega                Coffee Shop   
4            Arrochar              Bus Stop              Deli / Bodega   
5             Arverne             Surf Spot             Sandwich Place   
6             Astoria                   Bar  Middle Eastern Restaurant   
7     Astoria Heights          Burger Joint              Bowling Alley   
8          Auburndale    Italian Restaurant          Korean Restaurant   
9          Bath Beach    Chinese Restaurant                Pizza Place   
10  Battery Park City                  Park                      Hotel   
11          Bay Ridge    Italian Restaurant                        Spa   

   3rd Most Common Venue  4th Most Common Venue 5th Most Common Venue  \
0            Supermarket     Chinese Restaurant      Department Store   
1               Pharmacy           Liquor Store                  Food   
2            Pizza Place               Pharmacy           Yoga Studio   
3               Bus Stop    American Restaurant          Intersection   
4     Italian Restaurant  Outdoors & Recreation     Polish Restaurant   
5          Metro Station             Restaurant           Pizza Place   
6       Greek Restaurant             Hookah Bar    Seafood Restaurant   
7     Chinese Restaurant                 Bakery          Gourmet Shop   
8         Mattress Store   Fast Food Restaurant             Pet Store   
9     Italian Restaurant   Cantonese Restaurant              Pharmacy   
10                   Gym            Coffee Shop         Memorial Site   
11           Pizza Place     Chinese Restaurant      Greek Restaurant   

       6th Most Common Venue     7th Most Common Venue 8th Most Common Venue  \
0                        Spa             Grocery Store  Fast Food Restaurant   
1              Train Station                     Diner            Restaurant   
2                Fish Market                   Factory    Falafel Restaurant   
3                Yoga Studio               Flea Market                  Farm   
4   Mediterranean Restaurant                Bagel Shop            Taco Place   
5                 Playground               Coffee Shop            Donut Shop   
6                     Bakery  Mediterranean Restaurant           Pizza Place   
7                Pizza Place                    Hostel            Playground   
8                   Pharmacy        Miscellaneous Shop      Toy / Game Store   
9                 Donut Shop           Bubble Tea Shop           Gas Station   
10             Shopping Mall              Gourmet Shop             BBQ Joint   
11       American Restaurant                       Bar              Pharmacy   

    9th Most Common Venue      10th Most Common Venue  
0   Check Cashing Service                 Bus Station  
1          Farmers Market  Financial or Legal Service  
2                    Farm              Farmers Market  
3          Farmers Market        Fast Food Restaurant  
4            Liquor Store              Sandwich Place  
5              Board Shop                       Beach  
6       Indian Restaurant                        Café  
7                   Plaza               Deli / Bodega  
8       Mobile Phone Shop                       Train  
9    Fast Food Restaurant                 Coffee Shop  
10             Food Court                       Plaza  
11             Playground            Sushi Restaurant

### Clustering venues in New York Neighborhoods

Running k-Means algorithm to group neighborhood into clusters. Let take k = 5

In [130]:
# set number of clusters = 5
kclusters = 5

newyork_grouped_clustering = newyork_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(newyork_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
New dataframe of top 12 venues for each neighborhood

In [131]:
# add clustering labels
nyneighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

newyork_merged = df_newyork

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
newyork_merged = newyork_merged.join(nyneighborhoods_venues_sorted.set_index('Neighborhood'), on ='Neighborhood')

newyork_merged.head(12) # check the last columns!

Borough    Neighborhood   Latitude  Longitude  Cluster Labels  \
0       Bronx       Wakefield  40.894705 -73.847201               0   
1       Bronx      Co-op City  40.874294 -73.829939               0   
2       Bronx     Eastchester  40.887556 -73.827806               0   
3       Bronx       Fieldston  40.895437 -73.905643               0   
4       Bronx       Riverdale  40.890834 -73.912585               0   
5       Bronx     Kingsbridge  40.881687 -73.902818               0   
6   Manhattan     Marble Hill  40.876551 -73.910660               0   
7       Bronx        Woodlawn  40.898273 -73.867315               0   
8       Bronx         Norwood  40.877224 -73.879391               0   
9       Bronx  Williamsbridge  40.881039 -73.857446               0   
10      Bronx      Baychester  40.866858 -73.835798               0   
11      Bronx  Pelham Parkway  40.857413 -73.854756               0   

   1st Most Common Venue 2nd Most Common Venue 3rd Most Common Venue  \
0               Pharmacy         Deli / Bodega        Sandwich Place   
1            Bus Station            Bagel Shop     Accessories Store   
2                  Diner         Deli / Bodega              Bus Stop   
3                  River           Bus Station      Business Service   
4            Bus Station                  Park                   Gym   
5            Pizza Place                   Bar                Bakery   
6                    Gym        Sandwich Place           Coffee Shop   
7          Deli / Bodega                   Pub            Playground   
8            Pizza Place                  Bank                  Park   
9                    Bar             Nightclub            Soup Place   
10            Donut Shop   Fried Chicken Joint  Other Great Outdoors   
11           Bus Station           Pizza Place    Italian Restaurant   

        4th Most Common Venue 5th Most Common Venue 6th Most Common Venue  \
0                Dessert Shop           Gas Station        Ice Cream Shop   
1               Deli / Bodega   Fried Chicken Joint         Grocery Store   
2        Caribbean Restaurant           Bus Station         Metro Station   
3                       Plaza           Yoga Studio          Fishing Spot   
4                        Bank            Food Truck             Locksmith   
5   Latin American Restaurant    Mexican Restaurant        Sandwich Place   
6                 Yoga Studio      Department Store                 Diner   
7                 Pizza Place         Train Station   Rental Car Location   
8                    Pharmacy          Burger Joint         Grocery Store   
9        Caribbean Restaurant           Flea Market                  Farm   
10                Men's Store  Fast Food Restaurant        Mattress Store   
11         Frozen Yogurt Shop         Deli / Bodega                  Café   

   7th Most Common Venue 8th Most Common Venue 9th Most Common Venue  \
0             Donut Shop            Laundromat           Pizza Place   
1         Discount Store            Restaurant              Pharmacy   
2      Convenience Store    Chinese Restaurant    Seafood Restaurant   
3     Falafel Restaurant                  Farm        Farmers Market   
4                  Plaza           Yoga Studio                  Farm   
5    Fried Chicken Joint    Chinese Restaurant        Shipping Store   
6         Discount Store            Donut Shop           Pizza Place   
7         Cosmetics Shop            Donut Shop              Pharmacy   
8            Coffee Shop           Bus Station  Fast Food Restaurant   
9         Farmers Market  Fast Food Restaurant                 Field   
10           Bus Station             Pet Store                  Bank   
11           Gas Station                  Food      Sushi Restaurant   

   10th Most Common Venue  
0     Filipino Restaurant  
1        Basketball Court  
2               Juice Bar  
3    Fast Food Restaurant  
4          Farmers Market  
5      Spanish Restaurant  
6      Sea

#### Let's visualize the resulting clusters¶

In [132]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(
        newyork_merged['Latitude'], 
        newyork_merged['Longitude'], 
        newyork_merged['Neighborhood'], 
        newyork_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

### Clustering of New York Neighborhood venues

#### Ctuster 1

In [133]:
newyork_merged.loc[newyork_merged['Cluster Labels'] == 0, newyork_merged.columns[[1] + list(range(5, newyork_merged.shape[1]))]]

Neighborhood            1st Most Common Venue  \
0                    Wakefield                         Pharmacy   
1                   Co-op City                      Bus Station   
2                  Eastchester                            Diner   
3                    Fieldston                            River   
4                    Riverdale                      Bus Station   
5                  Kingsbridge                      Pizza Place   
6                  Marble Hill                              Gym   
7                     Woodlawn                    Deli / Bodega   
8                      Norwood                      Pizza Place   
9               Williamsbridge                              Bar   
10                  Baychester                       Donut Shop   
11              Pelham Parkway                      Bus Station   
12                 City Island               Seafood Restaurant   
13                Bedford Park                            Diner   
14          University Heights                      Pizza Place   
15              Morris Heights                    Deli / Bodega   
16                     Fordham                Mobile Phone Shop   
17                East Tremont                      Pizza Place   
18                  West Farms                      Bus Station   
19                High  Bridge                         Pharmacy   
20                     Melrose                      Pizza Place   
21                  Mott Haven                      Pizza Place   
22                 Port Morris        Latin American Restaurant   
23                    Longwood                   Sandwich Place   
24                 Hunts Point                     Gourmet Shop   
25                  Morrisania                      Bus Station   
26                   Soundview               Chinese Restaurant   
27                Clason Point                             Park   
28                 Throgs Neck                      Coffee Shop   
29                Country Club                   Sandwich Place   
30                 Parkchester                      Supermarket   
31          Westchester Square             Fast Food Restaurant   
32                    Van Nest                      Pizza Place   
33                 Morris Park                      Pizza Place   
34                     Belmont               Italian Restaurant   
35              Spuyten Duyvil                         Pharmacy   
36             North Riverdale                      Pizza Place   
37                  Pelham Bay               Italian Restaurant   
38               Schuylerville                      Pizza Place   
39              Edgewater Park               Italian Restaurant   
40                 Castle Hill                   Baseball Field   
41                   Olinville             Caribbean Restaurant   
42              Pelham Gardens                         Pharmacy   
43                   Concourse                    Grocery Store   
44                   Unionport                       Donut Shop   
45                    Edenwald                    Grocery Store   
46                   Bay Ridge               Italian Restaurant   
47                 Bensonhurst               Italian Restaurant   
48                 Sunset Park        Latin American Restaurant   
49                  Greenpoint                              Bar   
50                   Gravesend                           Lounge   
51              Brighton Beach                            Beach   
52              Sheepshead Bay                     Dessert Shop   
53           Manhattan Terrace                      Pizza Place   
54                    Flatbush               Mexican Restaurant   
55               Crown Heights                      Pizza Place   
56               East Flatbush                 Department Store   
57                  Kensington                    Grocery Store   
58             Windsor Terrace                             Park  

#### Ctuster 2

In [134]:
newyork_merged.loc[newyork_merged['Cluster Labels'] == 1, newyork_merged.columns[[1] + list(range(5, newyork_merged.shape[1]))]]

Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
192   Somerville                  Park           Yoga Studio   
203    Todt Hill                  Park           Yoga Studio   

    3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
192               Exhibit    Falafel Restaurant                  Farm   
203               Exhibit    Falafel Restaurant                  Farm   

    6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
192        Farmers Market  Fast Food Restaurant                 Field   
203        Farmers Market  Fast Food Restaurant                 Field   

    9th Most Common Venue      10th Most Common Venue  
192   Filipino Restaurant  Financial or Legal Service  
203   Filipino Restaurant  Financial or Legal Service

#### Ctuster 3

In [135]:
newyork_merged.loc[newyork_merged['Cluster Labels'] == 2, newyork_merged.columns[[1] + list(range(5, newyork_merged.shape[1]))]]

Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
179     Neponsit                 Beach           Yoga Studio   

    3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
179           Flea Market    Falafel Restaurant                  Farm   

    6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
179        Farmers Market  Fast Food Restaurant                 Field   

    9th Most Common Venue      10th Most Common Venue  
179   Filipino Restaurant  Financial or Legal Service

#### Ctuster 4

In [136]:
newyork_merged.loc[newyork_merged['Cluster Labels'] == 3, newyork_merged.columns[[1] + list(range(5, newyork_merged.shape[1]))]]

Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
207   Port Ivory                   Bar           Flea Market   

    3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
207               Factory    Falafel Restaurant                  Farm   

    6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
207        Farmers Market  Fast Food Restaurant                 Field   

    9th Most Common Venue      10th Most Common Venue  
207   Filipino Restaurant  Financial or Legal Service

#### Ctuster 5

In [137]:
newyork_merged.loc[newyork_merged['Cluster Labels'] == 4, newyork_merged.columns[[1] + list(range(5, newyork_merged.shape[1]))]]

Neighborhood       1st Most Common Venue       2nd Most Common Venue  \
255  Emerson Hill  Construction & Landscaping                 Yoga Studio   
303     Bayswater                  Playground  Construction & Landscaping   

    3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
255           Flower Shop    Falafel Restaurant                  Farm   
303           Yoga Studio          Fishing Spot               Factory   

    6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
255        Farmers Market  Fast Food Restaurant                 Field   
303    Falafel Restaurant                  Farm        Farmers Market   

    9th Most Common Venue      10th Most Common Venue  
255   Filipino Restaurant  Financial or Legal Service  
303  Fast Food Restaurant                       Field


## Results and Discussion <a name="results"></a>

The natural diversity of cities is always trivial.  The analysis of category of venues has shown that New York neighborhoods contain at least 431 uniques categories, while Toronto neighborhoods have only 233 categories.  This was clearly expected due to the fact that New York has been characterized as the world's premier financial center (Business Insider, Inc. 2014).

k-Means clustering method applied, in the same conditions, to the venues explored from neighborhoods of New York and Toronto into 10 most common clusters has shown different level of convergence.  New York clustering conververged at a third iteration while Toronto iterations went over a fifth rounds.  It trended that New York has far more diverse groups of business that Toronto. 

The results could be interpreted that for a qualified job seekers New york could be a better option because of multiple opportunities that Toronto, assuming that all political and public administrative influences were neglected.  But for small and medium enterprises investors, the method shows that Toronto could be a better option, considering that competition level in Toronto should be less agressive than in New York City.


## Conclusion <a name="conclusion"></a>

The analysis conducted here was conclusive assuming that all other factors: immigration policies, political, public administration etc, have no influence. This general comparison of business between New York and Toronto indicated the point was not to look at a certain "size" or "graduation" bu to explore the preponderance of groups of activities on on either sides.


## References <a name="references"></a>

[1] Toronto---Wikipedia

[2] New York ---Wikipedia

[3] Foursquare API

[4] "Top 8 Cities by GDP: China vs. The U.S." Business Insider, Inc. July 31, 2011. Retrieved July 29, 2014.